### ISSUE TITLE
Chat UX: Starred messages not reflected on other clients

### ISSUE THREAD

**Issue by yuvraj42** [Yogesh7920/meet.me#101]
Starring a message on one client doesn't reflect the change on other clients.

When a message is starred, other clients that had received that message also receive a notification about the starring in the content module, which is then passed to the Chat UX as a `ReceiveMessageData` object with the `Event` field set to `MessageEvent.Star` and the `MessageId` field telling which message has been starred. This information is how the UX on another client is notified that a message has been starred.

**Comment by Yogesh7920** [comment]
@RaswanthMurugan20 @Suchitray kindly fix this issue.

**Comment by Suchitray** [comment]
Starring is implemented the way the star feature works in WhatsApp. Only the user can see the starred messages.
