### ISSUE TITLE
Screenshare continuously send data just when visiting the page (without starting) 

### ISSUE THREAD

**Issue by Yogesh7920** [Yogesh7920/meet.me#102]
When I just visit the screen share page (without starting the screen share), data is continuously being sent. 
This can be observed by running the client in debug mode, going to the screen share page, and seeing the debug logs in both client and server. 

@RaswanthMurugan20 @pulavartivinay  @manassharma158 @NeerajPatil2000  kindly fix this issue.

**Comment by Yogesh7920** [comment]
And even though the screen share is constantly jamming the networking with their data. I should be able to send chat messages also right, cuz of the priority queue? 
But it is not working. I am unable to send a chat after I visit the screen share page. 
@subhash011 @Vamsi995 kindly fix this issue.

**Comment by subhash011** [comment]
I'm not able to reproduce this issue

**Comment by Yogesh7920** [comment]
> I'm not able to reproduce this issue, mostly it's fixed in the latest PR, can u try again

Yes now it seems to be working fine 👍🏻
