### ISSUE TITLE
ScreenSharing does not intialize the correct communicator on server

### ISSUE THREAD

**Issue by subhash011** [Yogesh7920/meet.me#105]
https://github.com/Yogesh7920/meet.me/blob/ec659f923bf2605884237529d9aab385fc874fc4/ScreenSharing/Server/ScreenShareServer.cs#L54

If you want to get the ServerCommunicator, you need to pass a boolean to the GetCommunicator method.
On server call it as: Communicator.GetCommunicator(false)

@manassharma158 @NeerajPatil2000, kindly fix this issue

**Comment by NeerajPatil2000** [comment]
I have made the required changes

**Comment by manassharma158** [comment]
Corresponding PR: https://github.com/Yogesh7920/meet.me/pull/108
