### ISSUE TITLE
UX Whiteboard : Argument Out of range Exception

### ISSUE THREAD

**Issue by Yogesh7920** [Yogesh7920/meet.me#107]
https://github.com/Yogesh7920/meet.me/blob/9675144f0f54392b6e28cd313014a884a9f6b715/Client/WhiteboardUX.cs#L1175

![image](https://user-images.githubusercontent.com/55453812/143689066-e500bd51-c09d-41f4-ade8-d9ecdc867b84.png)

When we draw a shape we get the right sidebar as shown, and when I click on delete the first time it deletes the shape as expected.
But even after deleting the sidebar still exists, and when I click on any other operation in the sidebar (e.g: delete, fill, etc), it is breaking the application

![sidebar](https://user-images.githubusercontent.com/55453812/143689016-50020046-27ac-4c9b-985d-905d435cfbc7.png)

@RaswanthMurugan20 @tripathiarpan20 @AniketRajpoot kindly fix this issue.

**Comment by AniketRajpoot** [comment]
Adding this line to following function would fix the bug in WhiteboardUX.cs, you can use this for further testing plus we would make PR as soon as possible : 
![Screenshot 2021-11-27 222010](https://user-images.githubusercontent.com/52102674/143690068-633f60b9-e72c-4625-ab52-44adafeebf9c.png)
