### ISSUE TITLE
Server should stop once the meet is over

### ISSUE THREAD

**Issue by Yogesh7920** [Yogesh7920/meet.me#132]
Once the meet is over (the last user has left), the server has to stop. 
The dashboard team and UX team kindly sort this issue. 

@bruise-88 @Rage-cmd @RaswanthMurugan20 @pulavartivinay

**Comment by bruise-88** [comment]
![image](https://user-images.githubusercontent.com/59951017/145014275-31d57d57-dde9-4889-a5a1-5af1b4a46adb.png)
@RaswanthMurugan20  we have created an event, please make the changes and subscribe to given event
