### ISSUE TITLE
Client not stopping after client leaves

### ISSUE THREAD

**Issue by Yogesh7920** [Yogesh7920/meet.me#133]
After the client clicks on the leave button, the window is closing, but the client itself is not stopping, it's still running. 

@bruise-88 @ragedjavelin @RaswanthMurugan20 @hps1991 kindly sort this issue out.

**Comment by Yogesh7920** [comment]
UX team, note that the window should close only after you get the notification from the client session manager (not as soon as the leave button is clicked)

**Comment by bruise-88** [comment]
Actually it should close as soon as client clicks leave button, it should just wait until session manager sends removeClient event to server ( call removeClient on main thread).

**Comment by Yogesh7920** [comment]
Oh i see, thanks. 
UX team, follow the same 

> Actually it should close as soon as client clicks leave button, it should just wait until session manager sends removeClient event to server ( call removeClient on main thread).
