### ISSUE TITLE
Whiteboard issues

### ISSUE THREAD

**Issue by Yogesh7920** [Yogesh7920/meet.me#138]
![image](https://user-images.githubusercontent.com/55453812/145258823-3aa28c33-b442-4e52-b904-5dfa78cbb894.png)

https://github.com/Yogesh7920/meet.me/blob/a345ff4c731f18d51da32a1a0ee5d5fe03fba04a/Client/WhiteboardUX.cs#L303

Steps to reproduce:
1. Run server and two clients say A and B.
2. Draw a shape in A. 
3. Select that shape in B
4. Let A fill that shape (or any operation such as rotate, etc), while B selected it.
5. B will automatically unselect that shape. 
6. Try selecting that shape with B. 
7. This error will be thrown

@RaswanthMurugan20 @AniketRajpoot @tripathiarpan20 
@manassharma158 @ak-303 @Parul664

**Comment by ak-303** [comment]
Server-update involves deleting and creating new shape, so the selected shape will get un-selected (This is an assumed feature). However, if there is null reference exception, this is most likely a Whiteboard UX side issue, which is minor, I guess. Anyway, please elaborate 4-5-6-7 step, and let us know if this error is constant. (Sometimes this kind of error just occur due to mouse events, which depends on system.)

**Comment by Yogesh7920** [comment]
I tried to reproduce the same error thrice and was successful, so I am confident these are valid steps. 
Elaboration:
Consider one shape that is drawn by A and selected by B. 
Let A do an operation on the shape, say fill a color. 
Now, select that same shape in B (after the color fill). 
Now the error will come in B.

**Comment by ak-303** [comment]
Yep then this selection is actually handled at UX-side itself, @tripathiarpan20 kindly look into this.

**Comment by Yogesh7920** [comment]
![image](https://user-images.githubusercontent.com/55453812/145261944-5bc03f4f-1d9b-4f30-82e4-2e0590519086.png)
https://github.com/Yogesh7920/meet.me/blob/15d6707b9a564b1eb66d54de067573f918beea00/Client/WhiteboardUX.cs#L294

This issue is coming when we have two users, one user is rotating a shape, and the other user is deleting it at almost the same time. 

P.S: This test case was given by sir itself during my demo, so most likely we may have to do this in the final demo also, so kindly fix this. 

@RaswanthMurugan20 
@tripathiarpan20 @AniketRajpoot 
@manassharma158 
@ak-303 @Parul664

**Comment by tripathiarpan20** [comment]
It seems like there was some miscommunication, as apparently the case in line 2188 of `WhiteboardUX.cs` would never occur.

In line 2199 of `WhiteboardUX.cs`, replace the case with the snippet given below:
``` C
case Operation.MODIFY:
                        // If the operation is a deletion operation, unselect the shape before deletion
                        if (received[i].UxOperation == UXOperation.DELETE && this.shapeManager.selectedShapes.Count > 0 && this.shapeManager.selectedShapes.Contains(received[i].WindowsShape.Uid))
                        {`
                            this.GlobCanvas = this.shapeManager.UnselectAllBB(this.GlobCanvas, this.WBOps);
                        }
                        //If the operation is MODIFY, directly render it onto the Canvas
                        if (received[i].WindowsShape == null) Trace.WriteLine("RenderUXElement received null");
                        else if (received[i].WindowsShape is System.Windows.Shapes.Polyline) GlobCanvas = this.freeHand.RenderUXElement(new List<UXShape> { received[i] }, GlobCanvas, WBOps);
                        else GlobCanvas = this.shapeManager.RenderUXElement(new List<UXShape> { received[i] }, GlobCanvas, WBOps);

                        break;
```

This change in code fixed the aforementioned bug on trial.

**Comment by ak-303** [comment]
This is again the same issue because of selection. I handled both of these cases at client and server level. If it still persists and is from state managing side @tripathiarpan20 let me know.

**Comment by ak-303** [comment]
> ![image](https://user-images.githubusercontent.com/55453812/145261944-5bc03f4f-1d9b-4f30-82e4-2e0590519086.png)
> 
> https://github.com/Yogesh7920/meet.me/blob/15d6707b9a564b1eb66d54de067573f918beea00/Client/WhiteboardUX.cs#L294
> 
> This issue is coming when we have two users, one user is rotating a shape, and the other user is deleting it at almost the same time.
> 
> P.S: This test case was given by sir itself during my demo, so most likely we may have to do this in the final demo also, so kindly fix this.
> 
> @RaswanthMurugan20 @tripathiarpan20 @AniketRajpoot @manassharma158 @ak-303 @Parul664

This is again the same issue because of selection. I handled both of these cases at client and server level. If it still persists and is from state managing side @tripathiarpan20 let me know.

**Comment by ak-303** [comment]
> It seems like there was some miscommunication, as apparently the case in line 2188 of `WhiteboardUX.cs` would never occur.
> 
> In line 2199 of `WhiteboardUX.cs`, replace the case with the snippet given below:
> 
> ```c
> case Operation.MODIFY:
>                         // If the operation is a deletion operation, unselect the shape before deletion
>                         if (received[i].UxOperation == UXOperation.DELETE && this.shapeManager.selectedShapes.Count > 0 && this.shapeManager.selectedShapes.Contains(received[i].WindowsShape.Uid))
>                         {`
>                             this.GlobCanvas = this.shapeManager.UnselectAllBB(this.GlobCanvas, this.WBOps);
>                         }
>                         //If the operation is MODIFY, directly render it onto the Canvas
>                         if (received[i].WindowsShape == null) Trace.WriteLine("RenderUXElement received null");
>                         else if (received[i].WindowsShape is System.Windows.Shapes.Polyline) GlobCanvas = this.freeHand.RenderUXElement(new List<UXShape> { received[i] }, GlobCanvas, WBOps);
>                         else GlobCanvas = this.shapeManager.RenderUXElement(new List<UXShape> { received[i] }, GlobCanvas, WBOps);
> 
>                         break;
> ```
> 
> This change in code fixed the aforementioned bug on trial.

It will be better if you could commit this change and raise a PR 😅

**Comment by tripathiarpan20** [comment]
> > It seems like there was some miscommunication, as apparently the case in line 2188 of `WhiteboardUX.cs` would never occur.
> > In line 2199 of `WhiteboardUX.cs`, replace the case with the snippet given below:
> > ```
> > case Operation.MODIFY:
> >                         // If the operation is a deletion operation, unselect the shape before deletion
> >                         if (received[i].UxOperation == UXOperation.DELETE && this.shapeManager.selectedShapes.Count > 0 && this.shapeManager.selectedShapes.Contains(received[i].WindowsShape.Uid))
> >                         {`
> >                             this.GlobCanvas = this.shapeManager.UnselectAllBB(this.GlobCanvas, this.WBOps);
> >                         }
> >                         //If the operation is MODIFY, directly render it onto the Canvas
> >                         if (received[i].WindowsShape == null) Trace.WriteLine("RenderUXElement received null");
> >                         else if (received[i].WindowsShape is System.Windows.Shapes.Polyline) GlobCanvas = this.freeHand.RenderUXElement(new List<UXShape> { received[i] }, GlobCanvas, WBOps);
> >                         else GlobCanvas = this.shapeManager.RenderUXElement(new List<UXShape> { received[i] }, GlobCanvas, WBOps);
> > 
> >                         break;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This change in code fixed the aforementioned bug on trial.
> 
> It will be better if you could commit this change and raise a PR 😅

Sure, would first need confirmation that the second issue is fixed too before that 😅
