### ISSUE TITLE
Parameterless constructors to serialize a class

### ISSUE THREAD

**Issue by subhash011** [Yogesh7920/meet.me#30]
The dashboard module needs to have a parameterless constructor for the below classes:
1. [ClientToServerData](https://github.com/Yogesh7920/meet.me/blob/main/Dashboard/ClientToServerData.cs#L9)
2. [ServerToClientData](https://github.com/Yogesh7920/meet.me/blob/main/Dashboard/ServerToClientData.cs#L14)

If objects of these classes need to be sent across the network, they must have a parameterless constructor for the serializer to be able to serialize them.

**Comment by Yogesh7920** [comment]
@bruise-88. Make the required changes ASAP.

**Comment by bruise-88** [comment]
But it necessary for the class to have parameterized constructor.

**Comment by bruise-88** [comment]
Let me keep both

**Comment by subhash011** [comment]
You can have two constructors
