### ISSUE TITLE
Obtaining the communicator through the CommunicationFactory

### ISSUE THREAD

**Issue by subhash011** [Yogesh7920/meet.me#31]
To use the communicator to send data across the network, all modules have to obtain the communicator through the CommunicationFactory.GetCommunicator method.
The whiteboard module must do the same in the below mentioned files:
1. [ClientBoardCommunicator.cs](https://github.com/Yogesh7920/meet.me/blob/main/Whiteboard/Client/ClientBoardCommunicator.cs#L41)
2. [ServerBoardCommunicator.cs](https://github.com/Yogesh7920/meet.me/blob/main/Whiteboard/Server/ServerBoardCommunicator.cs#L40)

**Comment by Yogesh7920** [comment]
@manassharma158 make the required changes ASAP.
