### ISSUE TITLE
List of receiver ids given is null Exception thrown

### ISSUE THREAD

**Issue by Yogesh7920** [Yogesh7920/meet.me#64]
https://github.com/Yogesh7920/meet.me/blob/f2ff72d4b3e00b8e2379a2244b8551868ac9dc8d/Content/Client/ContentClient.cs#L117

The following exception is being thrown, when I try sending a message in chat. 
I think if receiverIds is null, it implies broadcast, but the exception is being thrown for it. 

Kindly make the required changes Content and UX team.
@SahilChaudhari23 @yuvraj42 
@RaswanthMurugan20 @Suchitray

**Comment by SahilChaudhari23** [comment]
actually empty list is expected, so use new int[] { } instead of null

**Comment by yuvraj42** [comment]
An empty array of receiver ids implies broadcast. A null is just an error.

**Comment by Yogesh7920** [comment]
I see, @RaswanthMurugan20 @Suchitray, make the required change asap.

**Comment by SahilChaudhari23** [comment]
@Suchitray  @RaswanthMurugan20 also please note that we have added argument exception for null and empty string.
