### ISSUE TITLE
Dashboard server subscribing more than once to networking

### ISSUE THREAD

**Issue by Yogesh7920** [Yogesh7920/meet.me#71]
The server side dashboard is subscribing to the communicator more than once thus communicator is throwing the exception: `System.ArgumentException: An item with the same key has already been added. Key: Dashboard`

https://github.com/Yogesh7920/meet.me/blob/83537aae96b5b1f55532196852a2da8a14ca8493/Dashboard/Server/SessionManagement/ServerSessionManager.cs#L46

fix this issue asap. 
@bruise-88 @Rage-cmd

**Comment by bruise-88** [comment]
This issue is not due to Dashboard module

**Comment by bruise-88** [comment]
![image](https://user-images.githubusercontent.com/59951017/143462339-6311b8d0-3050-4474-9c94-ca5f4e7c9cd4.png)
Please use SessionManagerFactory.GetServerSesssionManager() instead of running default constructor

**Comment by Yogesh7920** [comment]
@RaswanthMurugan20 @pulavartivinay kindly change make these changes asap.
