### ISSUE TITLE
Chat UX : KeyNotFound Exception

### ISSUE THREAD

**Issue by Yogesh7920** [Yogesh7920/meet.me#78]
https://github.com/Yogesh7920/meet.me/blob/2e8ca590ea5664b46d66c0b8f2104bf79dc1841e/Client/ViewModel/ChatViewModel.cs#L60

![image](https://user-images.githubusercontent.com/55453812/143536818-08949220-385b-4102-85f8-a7120fc3b1a9.png)

@RaswanthMurugan20 @Suchitray kindly fix this issue

**Comment by Yogesh7920** [comment]
Steps to reproduce: 
1. Create 2 client A and B and the server
2. Send a message "Hi" from A.
3. In client B , reply to A's message.
4. This exception is thrown in client B

**Comment by Suchitray** [comment]
When is this exception being thrown?

**Comment by Yogesh7920** [comment]
> When is this exception being thrown?

https://github.com/Yogesh7920/meet.me/issues/78#issuecomment-979727502
