### ISSUE TITLE
New client cannot download existing files

### ISSUE THREAD

**Issue by subhash011** [Yogesh7920/meet.me#82]
When a new client join in the middle of a call and tries to download an existing file upload, the below exception is raised.

Steps to reproduce:
- Start a server and a client
- Upload a file on the client
- Start another client and try to download the file

![image](https://user-images.githubusercontent.com/56479170/143560656-1f7a9558-7278-4c5c-9982-021fa58ec016.png)

https://github.com/Yogesh7920/meet.me/blob/a6ee6e8cd315bee2b3432c0cb7f4e21cafcb81ef/Content/Models/ChatContext.cs#L111

@SahilChaudhari23 @sameer38 pls look into this

**Comment by sameer38** [comment]
@yuvraj42 Its on client side
