### ISSUE TITLE
Thread exceptions due to UI elements not being able to be accessed in multiple threads

### ISSUE THREAD

**Issue by manassharma158** [Yogesh7920/meet.me#84]
Not able to access UI elements like Windows.Shape across multiple threads. This is apparently causing thread exceptions in Whiteboard and corresponding UX. A possible fix for this could be to create and use those UI elements in the same thread. Please fix accordingly @ak-303

**Comment by ak-303** [comment]
Raised a PR for the same: [ https://github.com/manassharma158/meet.me/pull/35]( https://github.com/manassharma158/meet.me/pull/35) 

Tested and verified with @tripathiarpan20. Now its working.
