### ISSUE TITLE
Chat UX: Unstarring messages

### ISSUE THREAD

**Issue by yuvraj42** [Yogesh7920/meet.me#87]
When the `ReceiveMessageData` object that UX receives has the event `Content.MessageEvent.Star`, it indicates that the starred status of the message has been toggled. So if the message wasn't starred, it now is, and if it was already starred, then it indicates it has been unstarred.

In the UX, the unstarring part seems to be missing. Once starred, a message appears starred forever, even if it may have been unstarred at the server database if the user had clicked on the star button again.

**Comment by Yogesh7920** [comment]
@RaswanthMurugan20 @Suchitray kindly fix this issue

**Comment by Suchitray** [comment]
Unstarring is not implemented by UX, once a msg is starred it is starred forever
